<a href="https://colab.research.google.com/github/dhieuSynova/dhieuSynova.github.io/blob/master/A4O1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Find n prime number



In [ ]:
def is_prime(num):
  if num > 1:  
    for i in range(2,num):  
      if (num % i) == 0:  
        return False  
    else:  
      return True
  elif num == 1:
    return True
  else:  
    return False

In [ ]:
input_num = int(input("Enter a number: "))  

start = 1
count = 0
while True:
  if is_prime(start):
    print(start)
    count += 1
  if count >= input_num:
    break
  start += 1

Enter a number: 12
1
2
3
5
7
11
13
17
19
23
29
31


In [ ]:
is_prime(-1)

False

#Fibonacci


In [ ]:
def get_fibos(n):
  fibonacci_numbers = [0, 1]
  for i in range(2, n):
    fibonacci_numbers.append(fibonacci_numbers[i-1]+fibonacci_numbers[i-2])
  return fibonacci_numbers

get_fibos(12)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [ ]:
!pip install numpy

In [4]:
import numpy as np
 
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))

print(point1)
print(point2)

# calculating Euclidean distance
# using linalg.norm()
dist = np.linalg.norm(point1 - point2)
 
# printing Euclidean distance
print(dist)

[1 2 3]
[1 1 1]
2.23606797749979


# Cosin between 2 vector

In [5]:
import math

def dotproduct(v1, v2):
  print(tuple(zip(v1, v2)))
  return sum((a*b) for a, b in zip(v1, v2))

def length(v):
  return math.sqrt(dotproduct(v, v))

def angle(v1, v2):
  print(dotproduct(v1, v2) / (length(v1) * length(v2)))
  return math.acos(dotproduct(v1, v2) / (length(v1) * length(v2)))

In [6]:
point1 = np.array((1, 2, 3))
point2 = np.array((2, -1, 0))

angle(point1, point2)

((1, 2), (2, -1), (3, 0))
((1, 1), (2, 2), (3, 3))
((2, 2), (-1, -1), (0, 0))
0.0
((1, 2), (2, -1), (3, 0))
((1, 1), (2, 2), (3, 3))
((2, 2), (-1, -1), (0, 0))


1.5707963267948966

In [7]:
dotproduct(point1, point2)

((1, 2), (2, -1), (3, 0))


0

In [8]:
print(length(point1) == np.sqrt(14))
print(length(point2) == np.sqrt(5))

((1, 1), (2, 2), (3, 3))
True
((2, 2), (-1, -1), (0, 0))
True


Matrix addtional

In [29]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 =  np.array([[1, 2, 3], [4, 5, 6]])

arr3 = np.array([[1, 3, -2], [4, 0, -3]])
arr4 = np.array([[-2, 3, 1], [-4, 0, 3], [2, -3, 4]])

In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
def sum_matrix(m1, m2):
  y1, x1 = m1.shape
  y2, x2 = m2.shape
  m3 = m1
  print(m3)
  
  if (x1 != x2 or y1 != y2):
    return false
  else:
    for i in range(y1):
      for j in range(x1):
        m3[i, j] += m2[i, j]
    return m3

print(arr1)
print(arr2)
sum_matrix(arr1, arr2)

[[ 2  4  6]
 [ 8 10 12]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


array([[ 3,  6,  9],
       [12, 15, 18]])

In [31]:
def mul_maxtrix(m1, m2):
  y1, x1 = m1.shape
  y2, x2 = m2.shape
  a = np.zeros(shape=(y1, x2))
  if (x1 != y2):
    return False
  else:
    for i in range(y1):
      for j in range(x2):
        a[i, j] = sum(m1[i, k] * m2[k, j] for k in range(x1))
    return a
mul_maxtrix(arr3, arr4)


array([[-18.,   9.,   2.],
       [-14.,  21.,  -8.]])

Palindrome

In [33]:
def isPalindrome(s):
  return s == s[::-1]  

In [35]:
isPalindrome('IOI')

True

In [36]:
isPalindrome('MADAM')

True

In [37]:
isPalindrome('Hello')

False

Check Password

In [50]:
import re

pwd_chain  = 'ABd1234@1,a F1#,2w3E*,2We3345'
pwd_arr =  pwd_chain.split(',')
for pwd in pwd_arr:
  print('All', pwd)
  print('Good', pwd) if (re.fullmatch(r'^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[$#@]).{8,20}$', pwd)) else None

All ABd1234@1
Good ABd1234@1
All a F1#
All 2w3E*
All 2We3345


Giải phương trình bậc 2

In [56]:
import numpy as np
def solve2ndFormula(a, b, c):
  if (a == 0):
    return False
  else:
    if (a + b + c == 0):
      return 1, c/a
    elif (a - b + c == 0):
      return -1, -1 * c / a
    else:
      delta = b ** 2 - 4 * a * c
      if delta < 0:
        return False
      elif delta == 0: 
        return ((-1 * b / (2 * a)), (-1 * b / (2 * a)))
      else: 
        # return False
        sDelta = np.sqrt(delta)
        return (-1 * b - sDelta) / (2 * a), (-1 * b + sDelta) / (2 * a)

In [58]:
solve2ndFormula(4, -2, -6)

(-1, 1.5)

In [60]:
solve2ndFormula(2, -7, 3)

(0.5, 3.0)

In [62]:
solve2ndFormula(3, 2, 5)

False

In [63]:
solve2ndFormula(1, -4, 4)

(2.0, 2.0)